version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./logs/php-fpm:/var/log/php-fpm
    links:
      - db
      - redis

  nginx:
    image: nginx:1.15.12-alpine
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/certs:/ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - php

  redis-overcommit:
    build: ./docker/redis
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  redis:
    image: 'redis'
    restart: 'always'
    ports:
      - "6379:6379"
    depends_on:
      - redis-overcommit

  elasticsearch:
    build: ./docker/elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default

volumes:
  db-data:
    driver: local